# Numpy Basics

# Ques 1 : Questions on Basic NumPy Array

In [ ]:
import numpy as np

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr1 = np.array([1,2,3,6,4,5])
#rev_arr1 = arr1[::-1]
rev_arr1 = np.flip(arr1)
print(rev_arr1)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
arr2 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat_arr2 = arr2.flatten(order='C')
ravel_arr2 = arr2.ravel(order='F')
# order='C' for row-wise flatten 'F' for column-wise flatten
print(flat_arr2)
print(ravel_arr2)

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a==b)

[[ True  True]
 [ True  True]]


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
# (i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values_x,counts_x = np.unique(x,return_counts=True)
most_freq_x = values_x[np.argmax(counts_x)]
indices = np.where(x == most_freq_x)[0]
print(indices)
print(most_freq_x)

#(ii)
y = np.array([1,1,1,2,3,4,2,4,3,3,])
values_y,counts_y = np.unique(y,return_counts=True)
most_freq_y = values_y[np.argmax(counts_y)]
indices = np.where(y == most_freq_y)[0]
print(indices)
print(most_freq_y)

[0 5 7 8 9]
1
[0 1 2]
1


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
#(i)
sum_all_elm = gfg.sum()
#(ii)
sum_row = gfg.sum(axis=1)
#(iii)
sum_col = gfg.sum(axis=0)
print(sum_all_elm)
print(sum_row)
print(sum_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix



In [ ]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
#(i)
sum_diag = np.sum(np.diagonal(n_array))
print(sum_diag)
#(ii),(iii)
eigenvalues,eigenvectors = np.linalg.eig(n_array)
print(eigenvalues)
print(eigenvectors)
#(iv)
inversematrix = np.linalg.inv(n_array)
print(inversematrix)
#(v)
determinant = np.linalg.det(n_array)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
#(i)
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
p_mul_q = np.matmul(p,q)
print(p_mul_q)
covar_pq = np.cov(p.flatten(),q.flatten())
print(covar_pq)

#(ii)
r = np.array([[1,2],[2,3],[4,5]])
s = np.array([[4,5,1],[6,7,2]])
r_mul_s = np.matmul(r,s)
print(r_mul_s)
covar_rs = np.cov(r.flatten(),s.flatten())
print(covar_rs)

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [ ]:
X = np.array([[2,3,4],[3,2,9]])
Y = np.array([[1,5,0],[5,10,3]])
inner_prod = np.inner(X,Y)
print(inner_prod)
outer_prod = np.outer(X,Y)
print(outer_prod)

from itertools import product
cartesian_prod = np.array([np.concatenate((a,b)) for a,b in product(X,Y)])
print(cartesian_prod)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


# Ques 2 : Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
array = np.array([[1,-2,3],[-4,5,-6]])
#(i)
abs_array = np.abs(array)
print(abs_array)

#(ii)
flat_array = array.flatten()
p_flat = np.percentile(flat_array,[25,50,75])
print(p_flat)
p_col = np.percentile(array,[25,50,75],axis=0)
print(p_col)
p_row = np.percentile(array,[25,50,75],axis=1)
print(p_row)

#(iii)
mean_f = np.mean(flat_array)
median_f = np.median(flat_array)
sd_f = np.std(flat_array)
print(f'mean = {mean_f}, median = {median_f}, sd = {sd_f}')

mean_c = np.mean(array,axis=0)
median_c = np.median(array,axis=0)
sd_c = np.std(array,axis=0)
print(f'mean = {mean_c}, median = {median_c}, sd = {sd_c}')

mean_r = np.mean(array,axis=1)
median_r = np.median(array,axis=1)
sd_r = np.std(array,axis=1)
print(f'mean = {mean_r}, median = {median_r}, sd = {sd_r}')

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
mean = -0.5, median = -0.5, sd = 3.8622100754188224
mean = [-1.5  1.5 -1.5], median = [-1.5  1.5 -1.5], sd = [2.5 3.5 4.5]
mean = [ 0.66666667 -1.66666667], median = [ 1. -4.], sd = [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
A = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
A_floor = np.floor(A)
A_ceiling = np.ceil(A)
A_truncated = np.trunc(A)
A_rounded = np.round(A)
print(A_floor)
print(A_ceiling)
print(A_truncated)
print(A_rounded)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


# Ques 3 : Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [ ]:
Arr = np.array([10,52,62,16,16,54,453])
#(i)
sorted_Arr = np.sort(Arr)
print(sorted_Arr)

#(ii)
sorted_indices = np.argsort(Arr)
print(sorted_indices)

#(iii)
smallest_4 = np.sort(Arr)[:4]
print(smallest_4)

#(iv)
largest_5 = np.sort(Arr)[-5:]
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[10 16]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only


In [ ]:
Array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
#(i)
integer_only = Array[Array == Array.astype(int)]
print(integer_only)

#(ii)
float_only = Array[Array != Array.astype(int)]
print(float_only)

[1. 2. 3. 2.]
[1.2 2.2]


# Ques 4 : Based on Function to save Image

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

(b) Load the saved file into jupyter notebook?


In [6]:
import cv2
import numpy as np
import os

def img_to_array(path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if img is None:
        print("Error: Image not found or unable to read.")
        return

    if len(img.shape) == 2:
        print("Image is grayscale.")

        txt_filename = os.path.splitext(path)[0] + "_grayscale.txt"
        np.savetxt(txt_filename,img,fmt='%d')
        print(f"Grayscale image saved as text file: {txt_filename}")

    elif len(img.shape) == 3 and img.shape[2] == 3:
        print("Image is color (BGR).")

        img_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

        txt_filename = os.path.splitext(path)[0] + "_rgb.txt"

        reshaped = img_rgb.reshape(-1,3)
        np.savetxt(txt_filename,reshaped,fmt='%d',header='R G B',comments='')
        print(f"RGB image saved as text file: {txt_filename}")

    else:
        print("Unsupported image format or number of channels.")

img_to_array("example.jpeg")

Image is color (BGR).
RGB image saved as text file: example_rgb.txt
