1)	The Iris dataset is a classic example for demonstrating classification algorithms. It consists of 150 samples of iris flowers belonging to three species: Setosa, Versicolor, and Virginica, with four input features (sepal and petal length/width). Use SVC from sklearn.svm on the Iris dataset and follow the steps below:

  a)	Load the dataset and perform train-test split (80:20).

  b)	Train three different SVM models using the following kernels:
  Linear, Polynomial (degree=3), RBF

  c)	Evaluate each model using:

  •	Accuracy

  •	Precision

  •	Recall

  •	F1-Score

  d)	Display the confusion matrix for each kernel.

  e)	Identify which kernel performs the best and why.


In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

kernels = ["linear", "poly", "rbf"]

for k in kernels:
    if k == "poly":
        model = SVC(kernel=k, degree=3)
    else:
        model = SVC(kernel=k)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n===== Kernel: {k.upper()} =====")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average="macro"))
    print("Recall:", recall_score(y_test, y_pred, average="macro"))
    print("F1-Score:", f1_score(y_test, y_pred, average="macro"))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


===== Kernel: LINEAR =====
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

===== Kernel: POLY =====
Accuracy: 0.9
Precision: 0.923076923076923
Recall: 0.9
F1-Score: 0.8976982097186701
Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]

===== Kernel: RBF =====
Accuracy: 0.9666666666666667
Precision: 0.9696969696969697
Recall: 0.9666666666666667
F1-Score: 0.9665831244778612
Confusion Matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


2)	SVM models are highly sensitive to the scale of input features. When features have different ranges, the algorithm may incorrectly assign higher importance to variables with larger magnitudes, affecting the placement of the separating hyperplane. Feature scaling ensures that all attributes contribute equally to distance-based computations, which is especially crucial for kernels like RBF or polynomial.

  A) Use the Breast Cancer dataset from sklearn.datasets.load_breast_cancer.

  B) Train an SVM (RBF kernel) model with and without feature scaling (StandardScaler). Compare both results using:
  
  •	Training accuracy
  
  •	Testing accuracy

  C) Discuss the effect of feature scaling on SVM performance.


In [6]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# ------------------------
# Model WITHOUT Scaling
# ------------------------
model_no_scale = SVC(kernel="rbf")
model_no_scale.fit(X_train, y_train)

train_acc_no = model_no_scale.score(X_train, y_train)
test_acc_no = model_no_scale.score(X_test, y_test)

print("\n=== WITHOUT SCALING ===")
print("Training Accuracy:", train_acc_no)
print("Testing Accuracy:", test_acc_no)

# ------------------------
# Model WITH Scaling
# ------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_scaled = SVC(kernel="rbf")
model_scaled.fit(X_train_scaled, y_train)

train_acc_scaled = model_scaled.score(X_train_scaled, y_train)
test_acc_scaled = model_scaled.score(X_test_scaled, y_test)

print("\n=== WITH SCALING ===")
print("Training Accuracy:", train_acc_scaled)
print("Testing Accuracy:", test_acc_scaled)


=== WITHOUT SCALING ===
Training Accuracy: 0.9186813186813186
Testing Accuracy: 0.9298245614035088

=== WITH SCALING ===
Training Accuracy: 0.9824175824175824
Testing Accuracy: 0.9824561403508771


SVMs compute distances in feature space, and when one feature has a much larger numeric range than others, it dominates the distance calculation. That distorts the shape of the decision boundary and leads to poor performance, especially for nonlinear kernels like RBF.
After scaling, all features contribute equally, leading to a smoother and more accurate separating hyperplane. This usually improves both training and testing accuracy, as seen in the results.